---
- hosts: all
  become: true
  tasks:
    - name: install apache and php packages for Red Hat
      dnf:
        name:
          - httpd
          - php
        state: latest
        update_cache: yes
      when: ansible_distribution == "RedHat"
